name: GHAction example

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'
  pull_request:
    branches:
      - '**'

env:
  GHCR_USERNAME: nastkap

jobs:
  build-and-scan:
    name: Build, scan, and push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4
      
      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/nastkap/z2
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: |
            type=registry,ref=ghcr.io/nastkap/z2:cache
          cache-to: |
            type=registry,ref=ghcr.io/nastkap/z2:cache
          tags: ${{ steps.meta.outputs.tags }}

      - name: Analyze for critical and high CVEs
        id: docker-scout-cves
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ steps.meta.outputs.tags }}
          sarif-file: sarif.output.json
          summary: true
      
      - name: Upload SARIF result
        id: upload-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif.output.json

      - name: Check vulnerability scan results
        run: |
          CRITICAL_COUNT=$(jq '.runs[].results | map(select(.ruleId | contains("CRITICAL"))) | length' sarif.output.json)
          HIGH_COUNT=$(jq '.runs[].results | map(select(.ruleId | contains("HIGH"))) | length' sarif.output.json)
          if [ "$CRITICAL_COUNT" -gt 0 ] || [ "$HIGH_COUNT" -gt 0 ]; then
            echo "Critical or High vulnerabilities found. Failing the job."
            exit 1
          fi

      - name: Push Docker image to GHCR
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=ghcr.io/nastkap/z2:cache
          cache-to: |
            type=registry,ref=ghcr.io/nastkap/z2:cache
          tags: ${{ steps.meta.outputs.tags }}

